.\"Man page for declutter, by Dave Henderson.
.TH declutter 1 "2026 May 22"
.SH NAME
\fIdecluter\fR - data management




.SH SYNOPSIS

.B declutter [OPTIONS] ACTION SOURCE [TARGET] [STORED]

ACTIONS:
  -a   archives data
          - the TARGET value is not used
  -d   deduplicates data
          - the TARGET value can be used for comparison between dirs,
            otherwise the SOURCE will be deduplicated
  -e   cleans empty directories
          - the TARGET value is not used
  -m   cleans mismatched data
          - the SOURCE needs to contain the desired data (clean)
          - the TARGET needs to contain the additional data (dirty)

  --help      shows this screen
  --version   displays the software version

OPTIONS:
  -A   ignore data after this date: YYYY-MM-DD HH:MM:SS
  -B   ignore data before this date: YYYY-MM-DD HH:MM:SS
  -D   use and existing deduplication database: NAME
  -H   include hidden files and folders
  -P   directory prefix to remove when moving data: PREFIX
  -Y   perform a trial run with no changes made (dryrun)




.SH TOC

1.  DESCRIPTION
2.  CONFIG
3.  PARAMETERS
4.  ACTIONS
5.  OPTIONS
6.  EXAMPLES
7.  BUGS
8.  COPYRIGHT
9.  AUTHORS




.SH DESCRIPTION

.I declutter
is a lightweight script to perform a variety of tasks allowing an admin to
manage user-generated data - moving or deleting it. Contact our staff to
request additional features to be added in future releases.

Currently this project can perform a variety of operations including:
  o Archive data using before or after dates
  o Clean mismatched data between directories or drives
  o Deduplicate data between one or two directories
  o Remove empty directories
  o Each action can ignore files by date specifications
  o Hidden directories and files can optionally be included
  o Dryruns can test results before implementation
  o Each action can move or delete data matching criteria
  o Directory paths can be manipulated when moving data

Common outstanding features include:
  o A graphical user interface
  o Ability to color output
  o Ability to output to different formats




.SH CONFIG

Currently there are no config files associated with this utility.




.SH PARAMETERS

This utility can take several parameters to affect its operation. We will
cover the last three here, with the first and second contained in their
own section below.

Each action requires a SOURCE, and optionally TARGET, directories. These
will be the locations that get processed by the desired action. It is
important to note that only the -m action requires both of these values,
while being optional for -d, and unused by all others. However, each
action, if passed 'move', must include the STORED directory to know where
the targeted data should be moved. By default the path will be preserved,
but that can be adjusted via the -P option (see below).

To summarize:
  o The -m action requires both SOURCE and TARGET
  o The -d action can optionally accept TARGET
  o No other action uses TARGET
  o Each action requires STORED if moving targeted data




.SH ACTIONS

As with virtually all software, switches can be passed to modify its
operation. The below section covers each switch in detail, separating
the actions from the options. It is important to note that the options
actually need to proceed the actions when executing this software.

While not an action, by simply placing a blank file in the temp directory
with the name 'PID.stop' where 'PID' is the numeric value of the running
process, this software will stop operation immediately.

.B --help
Shows helpful information about the program.

.B --version
Displays the software version and exits.

.B -a
Over time user-generated data obvioulsy builds. Not only can this make the
working environment cluttered, but also force the need for larger storage
capacity in the live and backup drives. Archiving data is an easy way to
alieviate each of these issues with a single task. For large data sets, a
weekly, monthly, or semi-annual scheduled task can make sure that your live
environment stays as trim as possible!

This action only utilizes the SOURCE and optional STORED directory values.

.B -d
There are various scenarios where data can (accidentally) get duplicated.
As stated above, this can cause problems as storage capacity gets needlessly
consumed. Deduplicating files is a great way to recover drive space, some
times in significant quantities. This action makes the data of two drives or
directories unique.

To make this process work as fast as possible, files are compared using
their size. If two files have the same size, then a hash is generated for
both to test if the files are truly identical. This process requires the
generation of a database to keep track of all the information. See the -D
option below for more information.

Unless there is 100% certainty that the contents of a SOURCE directory
are unique, it is suggested to deduplicate that directory first before
using it as the comparison with a TARGET directory. Likewise, if there
are suspected duplicates in the TARGET directory that only reside in
that location and not also in SOURCE, you would need to deduplicate that
directory by itself beforehand. In other words, deduplicating does not
deduplicate the SOURCE, then the TARGET, and then the two against one
another. Each directory will need to have deduplication run on it
singularly before compared against one another if there is any doubt. One
last note, when using both SOURCE and TARGET, only the files in TARGET
will be moved or deleted.

This action can accept SOURCE, TARGET, and STORED directory values.

.B -e
Running any other action may lead to empty directories being left behind
once data has been moved or deleted. The removal of these directories is
not performed automatically in order to preserve existing path structures.
In the event that their retension is undesired, calling this script while
using this action will process all applicable directories. Additionally,
the date comparison of directories is ignored on all other actions except
this one since it only deals with those objects.

This action only utilizes the SOURCE and optional STORED directory values.

.B -m
There are not many instances when data sets become inconsistent, however,
it can happen. This action makes the data of two drives or directories the
same, with some conditions. First, the SOURCE and TARGET both need to have
the same data, with the TARGET having additional data that is not located
on the SOURCE. The second condition is that the data needs to be in the
same location in both places as this action simply isolates all data that
is not the same compared to the SOURCE. So even if the same file exists in
both SOURCE and TARGET, but is is a different directory on the TARGET, it
will be processed as being mismatched.

If the TARGET has some data that is the same on the SOURCE, then the data
sets will become similar after running this action.

In short, whatever data is the same, and in the same location between the
SOURCE and TARGET, is considered matching. Any other data is considered
mismatched and will be processed.

This action requires SOURCE, TARGET, and optionally STORED values.




.SH OPTIONS

To adjust the behavior of actions, you can pass one or more options when
executing this software. Remember that these actually need to proceed the
action switch!

.B -A EPOCH
Each action can be instructed to ignore files based on their modification
dates. Using this option will ignore all files (not directories) that
have a time stamp after the specified epoch. The format of the associated
value is in 24 hour format using the syntax: 'YYYY-MM-DD HH:MM:SS'

.B -B EPOCH
Like its counterpart above, this option ignores all files before the given
epoch.

.B -D DATABASE
When deduplicating data, there may be instances where the same directory
has been copied more than once. As a result, the deduplication process may
need to occur multiple times. To speed up this process you can reuse the
database created from the first run, however, the SOURCE value must remain
the same between the runs, and no data within it can be modified until the
entire deduplication process has completed. This option is only valid when
deduplicating.

.B -H
This switch controls whether hidden files and directories will be processed.
By default, these files are ignored. Passing this switches includes them.

.B -P
There may be times when portions of the path may need to be removed, when
moving targeted data. Simply pass the desired path prefix as the value to
this option and it will be removed in TARGET.

.B -Y
If you want to see exactly what is going to take place before running the
actual command, use this switch to perform a dryrun first.




.SH EXAMPLES

The below list shows various examples for using this software. This list
is not exhaustive and does not indicate modifications using any options.

Archive data before May 1st 2025 to /mnt/archive:
     declutter -A '2025-05-01 00:00:01' -a move /mnt/nas /mnt/archive

Separate live data after May 1st 2025 to /mnt/live:
     declutter -B '2025-05-01 00:00:01' -a move /mnt/nas /mnt/live

Deduplicate a single directory, ignorning newer additions
     declutter -A '2025-05-01 00:00:01' -d delete /home/user/Videos

Deduplicate two directories moving the duplicates to /opt/dupes
     declutter -d move /mnt/sda1/files /mnt/sdb1/data /opt/dupes

Remove empty directories:
     declutter -e delete /mnt/nas/data

Delete mismatch data (including hidden) between two drives:
     declutter -H -m delete /mnt/sdb1 /mnt/sdc1

Move mismatched (non-hidden) data between two drives to /opt/diff:
     declutter -m copy /mnt/sdb1 /mnt/sdc1 /opt/diff




.SH BUGS

There are no known bugs as of May 2026.

Please visit our website for the latest list of opened bug reports for
this software project - http://www.cliquesoft.org.




.SH COPYRIGHT

Copyright (C) 2016-2026 Cliquesoft

Unless a valid Cliquesoft Private License (CPLv1) has been purchased for your
device, this software is licensed under the Cliquesoft Public License (CPLv2)
as found on the Cliquesoft website at www.cliquesoft.org.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the appropriate Cliquesoft License for details.

You should have received a copy of the Cliquesoft Public License v2 with the
software itself; if not, please visit our website for the complete document:

   https://www.cliquesoft.org




.SH AUTHORS

Dave Henderson <daveh@cliquesoft.org>

