.\"Man page for declutter, by Dave Henderson.
.TH declutter 1 "2026 May 22"
.SH NAME
\fIdecluter\fR - data management




.SH SYNOPSIS

.B declutter [OPTIONS] ACTION SOURCE [TARGET] [STORED]

ACTIONS:
  -a   archives data
          - the TARGET value is not used
  -d   deduplicates data
          - the TARGET value can be used for comparison between dirs,
            otherwise the SOURCE will be deduplicated
  -e   cleans empty directories
          - the TARGET value is not used
  -m   cleans mismatched data
          - the SOURCE needs to contain the desired data (clean)
          - the TARGET needs to contain the additional data (dirty)

  --help      shows this screen
  --version   displays the software version

OPTIONS:
  -A   ignore data after this date: YYYY-MM-DD HH:MM:SS
  -B   ignore data before this date: YYYY-MM-DD HH:MM:SS
  -D   use and existing deduplication database: NAME
  -H   include hidden files and folders
  -N   perform a trial run with no changes made (dryrun)
  -P   directory prefix to remove when moving data: PREFIX




.SH TOC

1.  DESCRIPTION
2.  CONFIG
3.  PARAMETERS
4.  ACTIONS
5.  OPTIONS
6.  EXAMPLES
7.  BUGS
8.  ACKNOWLEDGEMENTS
9.  COPYRIGHT
10. AUTHORS




.SH DESCRIPTION

.I declutter
is a lightweight script to perform a variety of tasks allowing an admin to
manage user-generated data - moving or deleting it. Contact our staff to
request additional features to be added in future releases.

Currently this project can perform a variety of operations including:
  o Archive data using before or after dates
  o Clean mismatched data between directories or drives
  o Deduplicate data between one or two directories
  o Remove empty directories
  o Each action can ignore files by date specifications
  o Hidden directories and files can optionally be included
  o Dryruns can test results before implementation
  o Each action can move or delete data matching criteria
  o Directory paths can be manipulated when moving data

Common outstanding features include:
  o A graphical user interface
  o Ability to color output
  o Ability to output to different formats




.SH CONFIG

Currently there are no config files associated with this utility.




.SH PARAMETERS

This utility can take several parameters to affect its operation. We will
cover the last three here, with the first and second contained in their
own section below.

Each action requires a SOURCE, and optionally TARGET, directories. These
will be the locations that get processed by the desired action. It is
important to note that only the -m action requires both of these values,
while being optional for -d, and unused by all others. However, each
action, if passed 'move', must include the STORED directory to know where
the targeted data should be moved. By default the path will be preserved,
but that can be adjusted via the -P option (see below).

Unless there is 100% certainty that the contents of a SOURCE directory
are unique, it is suggested to deduplicate that directory first before
using it as the comparison with a TARGET directory. Likewise, if there
are suspected duplicates in the TARGET directory that only reside in
that location and not also in SOURCE, you would need to deduplicate that
directory by itself beforehand. In other words, deduplicating does not
deduplicate the SOURCE, then the TARGET, and then the two against one
another. Each directory will need to have deduplication run on it
singularly before compared against one another if there is any doubt. One
last note, when using both SOURCE and TARGET, only the files in TARGET
will be moved or deleted.

To summarize:
  o The -m action requires both SOURCE and TARGET
  o The -d action can optionally accept TARGET
  o No other action uses TARGET
  o Each action requires STORED if moving targeted data




.SH ACTIONS

As with virtually all software, switches can be passed to modify its
operation. The below section covers each switch in detail, separating
the actions from the options. It is important to note that the options
actually need to proceed the actions when executing this software.

While not an action, by simply placing a blank file in the temp directory
with the name 'PID.stop' where 'PID' is the numeric value of the running
process, this software will stop operation immediately.

.B --help
Shows helpful information about the program.

.B --version
Displays the software version and exits.

.B -a
Over time user-generated data obvioulsy builds. Not only can this make the
working environment cluttered, but also force the need for larger storage
capacity in the live and backup drives. Archiving data is an easy way to
alieviate each of these issues with a single task. For large data sets, a
weekly, monthly, or semi-annual scheduled task can make sure that your live
environment stays as trim as possible!

This action only utilizes the SOURCE and optional STORED directory values.

.B -d
There are various scenarios where data can (accidentally) get duplicated.
As stated above, this can cause problems as storage capacity gets needlessly
consumed. Deduplicating files is a great way to recover drive space, some
times in significant quantities.

This action only can accept SOURCE, TARGET, and STORED directory values.

.B -e
Running any other action may lead to empty directories being left behind
once data has been moved. It is recommended to re-run this utility
aftewards to remove these as a follow-up. This step is not performed
automatically in order to preserve directory structures.


LEFT OFF


.B -f FILES
While not a routine task, there may be times when it is useful to find the
package that a particular file belongs to. This action will allow you to
enter one or more files and search which local packages contains them.

.B -i
The cornerstone of all packages managers, this switch performs the actual
installation of packages so that users don't have to find, compile, and
install software themselves. The packages, or dependencies, can be local
or remote. If no PACKAGE(S) value is passed, then all packages in the
DIR_OPTION (or -S location) will be processed.
If speed is a necessity, and all packages and their dependencies are in
source directory, a '-D none' switch can be included to skip that check.

.B -l
To list the packages currently installed, use this switch. Currently the
output uses a verbose 2 line per package layout containing a plethora of
information about each package - provided the .info files are also present
in the DIR_INST directory. Users can pass specific packages to list, or
process all installed software without a PACKAGE(S) value.
NOTE: There are plans to reduce this to one line in a future version.

.B -m NAME DIRECTORY
This switch can be used to create a package file for distribution and will
bundle all the files in a passed directory. With the presence of a .make
file, pax will execute it to compile software before the packaging phase
takes place. This will enable package maintainers to include their .make
file alongside the packaged software so anyone can easily build from
source.

Unlike other switches, this one can only process one package at a time,
with the PACKAGE(S) value being used as the name of the created package.
This value can still be given in a text file, but only one name can be
included per execution. The other mandatory value is a DIRECTORY (or -S)
value to indicate the location of the files/source code to process.

If no .make file is present, then the passed directory will be considered
the root level for the package being created. If a .make file does exist,
then it needs to be named using the FILE_SCHEMA syntax with a .make file
extension, and placed directly inside the passed directory. Likewise, the
source code directory needs to be in the same location. Its name, however,
if of no value to pax since that will be handled by the .make script. The
compile process must install the created software into a staging directory
named 'project'. The layout should look like:
   /tmp/staging/
           PACKAGE.make
           PACKAGE-source-code-dir/
           project/

.B -o [NAME] [clear]
While there is not a package server manager yet, this switch will be used
by client devices to enable remote administration of packages. This will
be accomplished by using a value similar to:
   FIFO_SERVER='/sshfs/directory/device_NIC_MAC'
to enable network admins to remotely manage packages installed on devices
under their control, including the (un)installation, updating, and repair
of any software.

To give the fifo a different name, you can either modify the FIFO_SERVER
value in the config file, or pass a new name as a value to the -o switch.
In the event that a fifo was left behind due to some type of error, a
cleanup can be made by passing a trailing 'clear' to the pax command.

.B -t VALUE
Sometimes it is helpful to see dependency trees to packages. This switch
offers two different modes to show you this information. Using a value of
'relies' will display the dependencies that the passed package(s) rely on.
Contrarily, a value of 'reliant' will show all the packages that rely on
the ones passed.

.B -u VALUE
This action offers a range of uninstallation modes to handle your needs.
The first mode, 'unload', simply uninstalls the software files from your
device, leaving behind the config and package files for a quick reinstall.
The 'unlist' value performs the same tasks as 'unload', but additionally
removes the package from the LIST_LIVE (or -L list). If the software will
no longer be used, passing a 'delete' command will unlist and delete the
associated package files, leaving the configs untouched. To remove even
the package config files, use a 'purge' value to completely remove all
traces of the software from the device. Keep in mind that none of these
commands affect any data generated by the software, only the software
itself.

The last mode, is 'update', and as the name implies it's for updating
currently installed software to a new version. Unless overwritten, a
restore point is generated for the old version before the new one gets
installed. When performing this action, you need to be in the directory
containing the update so that the -S and DIRECTORY values can operate
as designed (the former being where the existing package file is located
and the latter being the path were the package is installed to).

To summarize:
  o 'unload' - removes application files
  o 'unlist' - unloads and removes LIST_LIVE (or -L) entry
  o 'delete' - unlists and removes package files
  o 'purge'  - deletes and removes config files
  o 'update' - unloads current version, installs new version

.B -v VALUE
There may be times when validating package data is necessary, especially
if software is malfunctioning. This action will enable you to validate the
package dependencies are installed by issuing a 'deps' value. It can also
validate that the files in a package are installed, have the appropriate
ownership/permissions, and either symlinked to the correct target, or that
each installed file is legitimate. Both tasks can be accomplished with a
'data' value, however, using 'hash' will extend validation of each copied
(not symlinked) file via hashes instead of the quicker comparison using
file sizes. The latter mode will take a bit longer to complete. If any
issues are found, you can use a 'fix' value to resolve them.

.B -z
This action is only useful when pax is installed in a distro using several
package managers, but it's not configured as the exclusive default. This
switch will sync the necessary cache files so that it can operate properly
in the OS. Even with this switch, alternating between various managers is
highly discouraged outside of testing environments.

If there are packages whose contents are installed some place other than
root, home, or DIR_LIVE, and have no installation marker, then make sure
to enter the root-level directory containing those files before executing
this action so that the packages can be properly processed.




.SH OPTIONS

To adjust the behavior of actions, you can pass one or more options with
each execution of pax. Remember that these actually need to proceed the
action switch!

.B -B
Used to indicate the device is booting so that packages can be processed
as configured using either a single or dual-phase installation. This also
sets DIRECTORY='/' and checks only REPO_SYSTEM. Users should never pass
this flag in a live environment.

.B -C VALUE
Specifies an alternative CPU architecture to process. This could be useful
for mixed 32/64 bit environments, or for building the OS for a different
target device.

.B -D VALUE
This switch controls how dependencies are processed. A value of 'none'
will prevent this step and affect only the packages pax is instructed to
process via a list, file, or directory. The 'default' value is the normal
mode of operation and will process dependencies. Some packages have
optional dependencies (e.g. documentation) that will also be processed by
using 'all' as the value. There is an additional mode, 'source', which
will work like 'default', but mandates that all the dependencies reside
in the passed -S location. It is impossible to combine the functionality
of 'all' and 'source' - at least presently.

To list packages as optional in the .deps file, use the following syntax:
   [OPTIONAL.EXT_SOFT|INSTALLLED.EXT_SOFT]

Unless '-D none' is used, the search order for dependencies is:
   REPO_SOURCE (-S), REPO_OPTION, REPO_SYSTEM, [REPO_SCHEMA]

.B -E VALUE[,VALUE,...]
In some cases a user might want more than the package files necessary
for an installation. For example, they may want a .make file to build
the package from source, or the .cpio file to include as part of the
base OS. Even downloading the .info file will provide extra package
info when using the -l action. Possible values include:
   all  - download all additional package files
   code - package source code
   cpio - initial ramdisk inclusion file
   info - package information
   list - package manifest listing
   make - package compile script

.B -F
Be careful with the inclusion of this option as it will force the action
to take place, even if dire consequences result!

.B -I VALUE[,VALUE,...]
In rare cases, there may be a need to ignore a dependency from getting
processed. For example, there may be a dependency that is still desired
to retain after another program that relies on it has been uninstalled.
Instead of adding a package to a flag file, this value can be passed
during the execution of pax.

.B -K VALUE
During normal operation, this flag would never be used since it changes
the kernel string attached to driver packages. However, if a kernel update
or an OS build for another device were required, this switch would become
useful.

.B -L VALUE
When installing a package, the default process adds the package to the
LIST_LIVE list. This can be foregone with a value of 'none', or placed
in the LIST_BOOT with a 'boot' value.

.B -M VALUE
Sets the mode for the installation of the package contents. The only two
values are 'copy' and 'link', with the latter referring to maintaining a
loopback mount to the package and symlinking its contents into the OS.
There are several advantages with this method including conservation of
storage space and the inability to manipulate a readonly file system.
This doesn't mean malicious activity can't take place, since symlinks can
be redirected, or replaced with an actual binary. But it does add some
more barriers.

If speed of operation is your primary goal, then you would want to use
the 'copy' value here, which is the default. If the OS uses a ramdisk,
then the speed is even greater than with attached storage.

.B -N VALUE[,VALUE,...]
For instances where storage space is at a premium, security is critical
(by miniming the attack vectors), or those that simply want the smallest
footprint possible, this option will allow only desired files to be
installed instead of the entire package. Using this switch will imply a
'-D none' value, so make sure that any lib packages necessary for the
desired files are also installed.

This can also be implemented within the .deps files themselves using the
following syntax:
   PACKAGE.EXT_SOFT{file1,file2,file3,...}

.B -O VALUE
Another unique feature of pax is that the output can be more than just the
default 'text'. Currently there are three other options with two of them
related to XML. The first is just 'xml' and will display the entire result
of the call at the end of execution. This means that the output will be
inside either a '<s>' (success) or '<f>' (failure) tag. The second is the
'xmLive' value that will display output as it is being processed, adding a
'<failure>' tag in the event of a problem being encountered.

The third additional option is 'fifo' that will output text to a named
pipe file. The long term goal is to build a server/client framework for
networks so that devices can be managed by an admin team using this
interface. Please note, that when using this value, the fifo must be
managed by the calling script or binary, and must use DIR_TEMP/output as
its location. This may be updated in future versions.

Since there may be a race condition while processing parameters, this one
should always be the first in the list to ensure the output is in the
format desired.

There are plans to also add 'json' and 'html' values in a future release.

.B -P
This switch simply prompts the user before implementing the requested
action, showing what is going to occur in the existing output.

.B -Q VALUE
Like most software that has the option to control verbosity, this switch
modifies the quietness of the output. Therefore, a value of 'all' will
actually produce no output, whereas a value of 'none' would make it the
most verbose it could be. Use 'errors' to reduce the output to only show
encountered problems, or 'verbose' to show slightly more than the default.

Since there may be a race condition while processing parameters, this one
should always be the first or second (if -O is also passed) in the list to
ensure the output is in the format desired.

.B -R VALUE
Without this flag, whatever action is passed works with the active local
or remote repo for packages. There may be instances where packages from
the restore points are desired. For example, lets say that a package got
updated on the device and now there's an issue. Until that issue can be
resolved, the user may want to rollback to their prior installation. To
accomplish this, the user simply needs to run pax with an appropriate -R
restore point value and the '-u update' action.

Another example may be where a user (accidentally) deleted software from
their device and now needs it replaced. This can be reversed by issuing
the -R switch with the corresponding restore point name and the -i action.

To view all the restore points use "-R '*' -l". To view the list within a
date, specify "-R 'YYYY-MM-DD' -l", or to see the packages contained in a
certain restore point, use "-R 'YYYY-MM-DD/Restore Point Name' -l". To
remove certain restore points, use the '-u {delete|purge}' action with the
date or complete path value for -R, to delete a group or individual point
respectively.

To summarize:
   o This option works with the -i, -l, and -u actions.
   o The prevent creating a restore point use '-R none' with -u
   o The format with -i is: 'YYYY-MM-DD/Restore Point Name'
   o The format with -l is: '*' or 'YYYY-MM-DD[/Restore Point Name]'
   o The format with -u is: 'YYYY-MM-DD[/Restore Point Name]'

.B -S VALUE
This switch changes the source location where the action obtains the
necessary packages. Depending on the action, this value may be a local
or network directory, or a remote repo (beginning with 'http' or 'ftp').

An interesting use of the -V, -S, and DIRECTORY values may be to perform
dianostics on an attached hard drive from another device.

.B -T VALUE
To prevent typing the full name of each package, this switch will fill in
this portion of the package name automatically. For example, lets say you
want to install the alsa-lib package. You can do so by using either the
full package name '-i alsa-lib' or '-T lib -i alsa'. This switch becomes
more pratical for a longer list of package names. Please note that all
packages listed must be of the same type.

.B -V VALUE
Sometimes unknown bugs are discovered once software is released to the
public, causing productivity issues. In this instance it is helpful to be
able to install a prior version, even temporarily until the problem can be
resolved. Using this switch will accomplish that task. The value to pass
will vary between distros as some may use actual software version numbers,
others may use values corresponding to releases of their OS. And like the
-m action, this one can also only process one package at a time.

This can also be implemented within the .deps files themselves using the
following syntax:
   PACKAGE.EXT_SOFT[1.2.3]

.B -X VALUE
Another unique feature of pax is the ability to proxy certain actions from
one device to another. This may be useful in situations where there is an
air gap between devices for security, or this may come in handy where the
Internet connection at a location is slow or intermittent but better at
another one.

This switch requires a value corresponding to the removable media mount
point so the pax command can be executed on another device. Once written,
plug the media in the other device and execute the 'proxy.sh' script found
in the 'pax' directory. Please note that the other device needs to also be
running Linux, or have the ability to process shell scripts. After running
the script, take the media back to the original device and run that same
script again. This will install the desired packages automatically.

Currently this switch can only work with the -c, -d, and -i actions.

.B -Y
If you want to see exactly what is going to take place before running the
actual command, use this switch to perform a dryrun. To get a complete log
of what will take place, add the '-Q none' switch and/or set DEBUG=1 in
the config file.

.B -Z
This switch simply adds color to the output.




.SH EXAMPLES

The below list shows various examples for using pax. This list is not
exhaustive and does not indicate modifications using any options.

Performing action with all packages [to current directory]:
     ${TEMP} -{ceilt}
Performing action with specific packages [to current directory]:
     ${TEMP} -{cdeilt} package1 package2
Performing action with package list [to current directory]:
     ${TEMP} -{cdeilt} packages.txt
Performing action with specific packages to/in a specified directory:
     ${TEMP} -{cdeilt} package1 package2 /target/path
Performing action with a package list to/in a specified directory:
     ${TEMP} -{cdeilt} packages.txt /target/path
Performing action with specific packages from/in a specified directory:
     ${TEMP} -S {URL|/source/path} -{cdeilt} package1 package2
Performing action with a package list from/in a specified directory:
     ${TEMP} -S {URL|/source/path} -{cdeilt} packages.txt
Performing action with all packages between specified directories:
     ${TEMP} -S {URL|/source/path} -{cdei} /target/path
Performing action with a package list between specified directories:
     ${TEMP} -S {URL|/source/path} -{cdei} packages.txt /target/path

Find files in available packages:
     ${TEMP} -f file1 file2
Find files in available packages from a filelist:
     ${TEMP} -f files.txt
Find files in packages within a specified directory:
     ${TEMP} -f file1 file2 /source/path
     ${TEMP} -S /source/path -f file1 file2
Install a specific version:
     ${TEMP} -V 1.2.3 -i package
Install a package from a valid restore point:
     ${TEMP} -R 'YYYY-MM-DD/Restore Point' -i package
List all restore points:
     ${TEMP} -R '*' -l
List all restore points in a valid date:
     ${TEMP} -R 'YYYY-MM-DD' -l
List all packages in a valid restore point:
     ${TEMP} -R 'YYYY-MM-DD/Restore Point' -l
Make a package for distribution:
     ${TEMP} -m package /path/containing/{package|source}
     ${TEMP} -S /path/containing/{package|source} -m package
     ${TEMP} -S /path/containing/{package|source} -m file
Open a fifo to operate pax:
     ${TEMP} -o
Open a fifo to operate pax in a specified directory:
     ${TEMP} -o /path/to/fifo
     ${TEMP} -S /path/to/fifo -o
Open a fifo to operate pax using a specific fifo:
     ${TEMP} -o name
Open a fifo to operate pax, clearing a prior failure:
     ${TEMP} -o clear
Open a fifo to operate pax, clearing and using specific fifo:
     ${TEMP} -o name clear
Proxy a download:
     ${TEMP} -X /mnt/sdb1 -d package1 package2
Proxy an install:
     ${TEMP} -X /mnt/sdb1 -i package1 package2
Unload a package:
     ${TEMP} -u unload package
Uninstall a package, leaving configs:
     ${TEMP} -u delete package
Uninstall a package, including configs too:
     ${TEMP} -u purge package
Uninstall a package, without a restore point:
     ${TEMP} -R none -u delete package
Update a package (uninstall old, install new):
     ${TEMP} -u update package
Delete a restore point(s):
     ${TEMP} -R 'DATE[/Restore Point]' -u {delete|purge}




.SH BUGS

There are no known bugs as of January 2026.

Please visit our website for the latest list of opened bug reports for
this software project - http://www.cliquesoft.org.




.SH ACKNOWLEDGEMENTS

This program is based on the various package managers currently in use
for the many Linux distros available today. We use them as a guide to
incorporate new features to expand the project.




.SH COPYRIGHT

Copyright (C) 2016-2026 Cliquesoft

Unless a valid Cliquesoft Private License (CPLv1) has been purchased for your
device, this software is licensed under the Cliquesoft Public License (CPLv2)
as found on the Cliquesoft website at www.cliquesoft.org.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the appropriate Cliquesoft License for details.

You should have received a copy of the Cliquesoft Public License v2 with the
software itself; if not, please visit our website for the complete document:

   https://www.cliquesoft.org




.SH AUTHORS

Dave Henderson

